# Generated by Django 3.1.4 on 2020-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='auther',
            field=models.CharField(default='dev', max_length=50),
            preserve_default=False,
        ),
    ]
