# Generated by Django 3.1.4 on 2020-12-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='auther',
            field=models.CharField(default='Dev', max_length=50),
        ),
    ]
