# Generated by Django 3.1.4 on 2020-12-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201229_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('Language', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.TextField(default='English', max_length=20),
        ),
    ]
